### ISSUE TITLE
Hello! I would like to ask about one of the modules used in Cerberus 

### ISSUE THREAD

**Issue by MetalMaxMX** [PhilMoe/cerberus#150] opened 2024-03-29 19:16 UTC
Hey! I would like to ask something. See, we are trying to get Cerberus-X on the FSF directory-listing, and we are looking at adding this project to the directory. After some discussion, we found this module here that looked concerning 
https://github.com/PhilMoe/cerberus/blob/develop/modules/opengl/gl.h

The license seems to be explicitly forbidding the sharing and usage of this header and we found this quite strange as gl2.h allows redistribution of it so if possible, we would like some clarification on what's happening with this header and if any info could be provided. 

Cheers!
MetalMaxMX

**Comment by PhilMoe** [comment] 2024-03-30 10:35
Hi @MetalMaxMX! Thanks for pointing this out! As I understand it the original author probably pushed this file accidentally. I am going to clean up the repository and erase or replace this file as good as possible. The file itself seemingly doesn't provide any actual functionality but was used for generation. @dawlane for vis.
Let me know if you have other questions.

**Comment by PhilMoe** [comment] 2024-03-30 11:54
Hi @MetalMaxMX! Thanks for pointing this out! As I understand it the original author probably pushed this file accidentally. I am going to clean up the repository and erase or replace this file as good as possible. It looks like it is used for the old mojo rendering functionality. @dawlane for vis.
Let me know if you have other questions.

**Comment by MetalMaxMX** [comment] 2024-03-31 09:49
Hello, and thanks for answering @PhilMoe! I would like to add a few more questions while at it. 

A) Do you happen to know if there are any other files with similar potential licensing issues? We want to make sure that Cerberus is 100% free software, since I believe it was released by its original author as a zlib codebase, as that was the original intent. But after discovering gl.h, well, we would now like to know more about what can be done to find any file that was pushed accidentally. 

B) On the itch.io website of Cerberus (see https://cerberus-x.itch.io/cerberus-x), there's a mention of a "proprietary mojo framework", one of the comments actually mentions this as being a relic of when Mark Sibly was still selling Monkey-X back in the day and that it should be fixed. Just to make 100% sure, but neither of the Mojos are proprietary right? Since they were both packaged with the original release I assume? (That is to say, that both are zlib-licensed as much as the rest of the codebase)  

C) We work with tagged releases, that is to say, we point to a specific version of the program on the directory-listing so users know which specific version has proper licensing rules that are consistent with the entries we file. I would like to know if there will be a tagged release in the future without gl.h or any other files with potential licensing issues? (so a new version, like 2024-X-Y) 

Thanks for your collaborations!
Cheers!
MetalMaxMX

**Comment by PhilMoe** [comment] 2024-03-31 16:27
Hey @MetalMaxMX! Here are some rather short and vage answers to your questions, but I hope that is enough for the moment.
A) No, I was surprised to get notice of that file and license and I am currently investigating a bit more. My current state of knowledge is: This file will be removed completely from the repo (including history) and should not have slipped in in the first place. 
There are some other open source tools used in Cerberus X that have their own license. 
The [sound library license](https://www.cerberus-x.com/cxDocs/Licence%20information.html) is mentioned explicitely in the docs.

B) All Cerberus X code besides the included other tools like glfw, metalangle, etc. is under the license stated [here in GitHub](https://github.com/PhilMoe/cerberus?tab=License-1-ov-file#License-1-ov-file). I couldn't find your mentioned proprietary mojo statement. These things need to be removed. 

C) Yes, I am planing to create tagged releases again. Well regarding the licenses I will have to investigate if there are things left that need some attention. 

I just recently took over the repo and I am in the process of getting the forum. So there is some work to do. I will make licensing a topic in the forum so I can come up with a list of licenses used by included tools. If you run into another thing just let me know for now. 

All the best!
Phil

**Comment by MetalMaxMX** [comment] 2024-04-01 13:32
Hello! Thank you so much for answering! 

I would like to clarify that the "proprietary mojo" statement was a remnant of that itch.io site, I checked once more and it seems like is not there in the description field anymore, only an user commenting on it about 4 years ago so now it's all fine since, well, is not mentioned over there. 

Also, awesome that we will get newer tagged releases too! We have an IRC meeting on Fridays to discuss this so I would like to leave this issue open so we can discuss a bit more about the next steps to take when it comes to Cerberus on FSF directory-meeting, once again, thank you for your input and I'll update you with any new findings or related once the next meeting comes and goes. 

Cheers!
MetalMaxMX

**Comment by PhilMoe** [comment] 2024-04-26 13:18
Hey @MetalMaxMX!

I just wanted to let you know that the issue is probably fixed. It took me some time to clean up the branches and stached things, but to me the current state looks promising. Let me know if you run into anything. BTW It might be good make a fresh clone or fork as there have probably been some changes behind the scenes. You can have a look [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github) for more info about the task.

Best regards,
Phil

**Comment by MetalMaxMX** [comment] 2024-04-26 17:54
Hello @PhilMoe!

Yes, I think that might be enough. Just to confirm one last time, but we work with tags/tagged releases in order to point to people to packages that are frozen and can be guaranteed to run with free software. I was wondering if the changes and cleaning of the branches also affected the current existing tagged releases on the repository? If you can confirm this, then feel free to close the issue. 

Cheers!
MetalMaxMX.

**Comment by PhilMoe** [comment] 2024-04-28 13:13
@MetalMaxMX The tags themselves should be fine, and the source packages attached to them in the releases seem to be updated as well. There are 81 tags with two source files each. I checked 10 of them randomly and didn't find any of the deleted files. 
I will close the issue once I checked all of them. 
Thanks again for your patience. 😃

**Comment by MetalMaxMX** [comment] 2024-04-30 18:56
@PhilMoe Sure, take your time. Thank you once again for making the efforts required to make this happen, it's a good day for free as in freedom software!

The best!
MetalMaxMX.

**Comment by PhilMoe** [comment] 2024-05-20 22:03
Hey @MetalMaxMX! 

I finally found a few bad binary packages that were bundled with some releases and deleted those attachments. All the other autogenerated release/tag source code packages are all verified clean. 
One thing I know now is that I will not bundle binary releases here on GitHub for sure. Only regular tag releases with source code as zip and tar.gz attached. 😅 
Hope that is fine for you as well!?

All the best
Phil

**Closed by PhilMoe** 2024-05-20 22:03 UTC

**Comment by MetalMaxMX** [comment] 2024-05-22 04:53
> Hey @MetalMaxMX!
> 
> I finally found a few bad binary packages that were bundled with some releases and deleted those attachments. All the other autogenerated release/tag source code packages are all verified clean. One thing I know now is that I will not bundle binary releases here on GitHub for sure. Only regular tag releases with source code as zip and tar.gz attached. 😅 Hope that is fine for you as well!?
> 
> All the best Phil

I am perfectly fine with it! Thank you very much for the efforts. I prefer to manually compile from source code anyway for a more optimized experience so this is not an issue for me. 

Cheers, 
MetalMaxMX.
